swagger: "2.0"
info:
  description: "FILL IT AFTERWARDS"
  version: "1.0.0"
  title: "Ban & Deletion Service v1"
  contact:
    email: "mert.oztekin@deliveryhero.com"
host: "TBD"
basePath: "/v1"
schemes:
- "http"
paths:
  /request:
    put:
      summary: "Create a new Deletion Request"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "header"
        name: X-Token
        description: "Token of the user or system to identify iteself"
        type: string
        required: true
      - in: "body"
        description: "Creates a new Deletion Request"
        required: true
        name: request
        schema:
          type: object
          properties:
            customer_id:
              type: string
              example: 123
            customer_email:
              type: string
              example: mail@domain.com
            entity_id:
              type: integer
              example: 3
            comment:
              type: string
              example: Customer requested on XX.XX.XXXX
      responses:
        200:
          description: "Success"
    get:
      summary: "Returns all Deletion Request which the user generated"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "header"
        name: X-Token
        description: "Token of the user or system to identify iteself"
        type: string
        required: true
      responses:
        200:
          description: "List of Deletion Requests. If the client is a system, it will return all requests which are waiting to be processed by the requester. If it is a user, it will return all requests generated by the user"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/DeletionRequestResponse"
  /request/{request_id}/status:
    post:
      summary: "Updates status of a deletion request by system"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "request_id"
        required: true
        description: "Id of deletion request"
        type: "integer"
      - in: "header"
        name: X-Token
        description: "Token of the user or system to identify iteself"
        type: string
        required: true
      - in: "body"
        name: "body"
        description: "Updates Deletion Request"
        required: true
        schema:
          type: "object"
          properties:
            status:
              type: "boolean"
            comment:
              type: "string"
      responses:
        200:
          description: "Success"
  /entity:
    get:
      summary: "Returns all entitites in the system"
      produces:
      - "application/json"
      parameters:
      - in: "header"
        name: X-Token
        description: "Token of the user or system to identify iteself"
        type: string
        required: true
      responses:
        200:
          description: "Successful operation."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Entity"
            example:
              - id: 1
                name: "Lieferheld"
              - id: 2
                name: "Foodora Germany"
              - id: 2
                name: "Mjam"
        400:
          description: "Invalid request"
definitions:
  DeletionRequestResponse:
    properties:
      request_id:
        type: "integer"
      customer_id:
        type: "string"
      customer_email:
        type: "string"
      entity_id:
        type: "integer"
      entity_name:
        type: "integer"
      comment:
        type: "string"
      date:
        type: "string"
      status:
        type: "array"
        items:
          $ref: "#/definitions/DeletionRequestServiceLog"
  DeletionRequestServiceLog:
    properties:
      service_name:
        type: "string"
      status: 
        type: "boolean"
      modified_at:
        type: "string"
      
  Entity:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"